server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
